### PR TITLE
fix: potential plugin crash when the project is closed. closes #26

### LINKED ISSUE #26: AlreadyDisposedException with  New UI after project start
I am using New UI with DataGrip. Project label triggers the attached exception after opening   a project. I am just using Label Color, no background image etc. I does not happen anytime just ocassionally. I did not find a reliable way to reproduce and force the exception. It happens randomly. 

Screenshot 2023-09-22 092028

com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.ide.util.PropertiesComponent because container is already disposed (container=Project(name=PRODUCTION, containerState=DISPOSE_COMPLETED, componentStore=.....\PRODUCTION) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:695)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage.projectLevelPropertiesComponent(ProjectLabelBackgroundImage.java:113)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage.hideImage(ProjectLabelBackgroundImage.java:125)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage.showImage(ProjectLabelBackgroundImage.java:83)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage.updateImage(ProjectLabelBackgroundImage.java:121)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage$1.componentMoved(ProjectLabelBackgroundImage.java:75)
	at java.desktop/java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:178)
	at java.desktop/java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:177)
	at java.desktop/java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:177)
	at java.desktop/java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:177)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6477)
	at java.desktop/java.awt.Component.processEvent(Component.java:6428)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Window.processEvent(Window.java:2078)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### PR DESCRIPTION
**Pull request by drinchev**

### CODE REVIEW

File: src/main/java/com/drinchev/projectlabel/resources/ui/ProjectLabelBackgroundImage.java [hunk 1]
```diff
@@ -109,11 +114,6 @@ private void setImageToIDE() {
         }
     }
 
-    private PropertiesComponent projectLevelPropertiesComponent() {
-        PropertiesComponent prop = project.getService(PropertiesComponent.class);
```
Comment (drinchev) [inline src/main/java/com/drinchev/projectlabel/resources/ui/ProjectLabelBackgroundImage.java:113]: Hi @simschla , as this might be the potential crash reason, described in #26 . I decided to get rid of this method and use the getter directly.

File: src/main/resources/META-INF/plugin.xml [hunk 2]
```diff
@@ -8,8 +8,6 @@
     <extensions defaultExtensionNs="com.intellij">
         <applicationService serviceImplementation="com.drinchev.projectlabel.preferences.ApplicationPreferences"/>
         <projectService serviceImplementation="com.drinchev.projectlabel.preferences.ProjectPreferences"/>
-        <projectService serviceImplementation="com.drinchev.projectlabel.ProjectLabel" />
```
Comment (drinchev) [inline src/main/resources/META-INF/plugin.xml:11]: IntelliJ suggested that I remove those, because they are now `final` classes.

File: src/main/java/com/drinchev/projectlabel/ProjectLabelStartupActivity.java [hunk 3]
```diff
@@ -2,20 +2,14 @@
...
 import com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage;
 import com.intellij.openapi.project.Project;
-import com.intellij.openapi.startup.ProjectPostStartupActivity;
-import kotlin.Unit;
-import kotlin.coroutines.Continuation;
+import com.intellij.openapi.startup.StartupActivity;
 import org.jetbrains.annotations.NotNull;
-import org.jetbrains.annotations.Nullable;
 
-public class ProjectLabelStartupActivity implements ProjectPostStartupActivity {
```
Comment (drinchev) [inline src/main/java/com/drinchev/projectlabel/ProjectLabelStartupActivity.java:11]: This was "experimental" and I couldn't pass the plugin validity check.

I tested it and works with `StartupActivity`.

File: src/main/java/com/drinchev/projectlabel/resources/ui/ProjectLabelBackgroundImage.java (hunk 1 above)
Comment (simschla) [reply src/main/java/com/drinchev/projectlabel/resources/ui/ProjectLabelBackgroundImage.java:113]: LGTM, although the actual fix is probably not removing the method but checking `project.isDisposed` beforehand 😉

File: src/main/resources/META-INF/plugin.xml [hunk 4]
```diff
@@ -8,8 +8,6 @@
...
-        <projectService serviceImplementation="com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage" />
```
Comment (simschla) [inline src/main/resources/META-INF/plugin.xml:12]: are these obsolete due to the annotations?

**Review by simschla — APPROVED** [review]
LGTM

File: src/main/java/com/drinchev/projectlabel/resources/ui/ProjectLabelBackgroundImage.java (hunk 1 above)
Comment (drinchev) [reply src/main/java/com/drinchev/projectlabel/resources/ui/ProjectLabelBackgroundImage.java:113]: I agree, however the return type is `PropertiesComponent` and in case the project is disposed I prefer to stop executing the flow further.

```
private PropertiesComponent projectLevelPropertiesComponent() {
      if (project.isDisposed()) {
            return; // Return what?
      }
      PropertiesComponent prop = project.getService(PropertiesComponent.class);
      return prop;
```

Comment (drinchev) [reply src/main/java/com/drinchev/projectlabel/resources/ui/ProjectLabelBackgroundImage.java:113]: Of course if you have a better suggestion let me know.

File: src/main/resources/META-INF/plugin.xml (hunk 4 above)
Comment (drinchev) [reply src/main/resources/META-INF/plugin.xml:12]: No clue, why exactly, but once I moved the class of the service to `final` and IntelliJ suggested that since this is not a complex component I can leave these out.
